x = input("Enter your name :")
print("Hello, {}!".format (x))
b = input("Enter your age :")
print ("your age is, {}!".format(b))
c = input("Enter Where your live :")
print ("you live in, {}!".format(c))
